In [1]:
import numpy as np
import pandas as pd

In [2]:
constituents_df = pd.read_excel('Constituent Data - Abbeywood University.xlsx', index_col='Alumni ID')

In [3]:
constituents_df.head()

,Full Name,Gender,Date of Birth,Age,Deceased,Nationality,Home City,Home Country,Phone Number,Email
Alumni ID,,,,,,,,,,
1,Thomas IvyTurner,Male,1941-03-06,85,NaN,British,Birmingham,United Kingdom,4.475469e+11,tivyturner@abbeywood.ac.uk
2,James WestJones,Male,1955-02-21,71,NaN,Spanish,Toronto,Canada,1.037056e+10,jwestjones@abbeywood.ac.uk
3,Charlotte IvyClark,Female,1967-02-02,59,NaN,British,Manchester,United Kingdom,4.472289e+11,civyclark@abbeywood.ac.uk
4,Georgia IvyTurner,Female,1949-06-12,77,NaN,British,London,United Kingdom,4.475057e+11,givyturner@abbeywood.ac.uk
5,Olivia GlenClark,Female,1945-04-06,81,NaN,British,Manchester,United Kingdom,NaN,oglenclark@abbeywood.ac.uk

In [4]:
constituents_df[ constituents_df['Deceased'].notna() ].count()

Full Name        884
Gender           884
Date of Birth    884
Age              884
Deceased         884
Nationality      884
Home City        884
Home Country     884
Phone Number     796
Email            872
dtype: int64

In [5]:
constituents_df.describe()

                    Date of Birth           Age  Phone Number
count                       10000  10000.000000  9.502000e+03
mean   1968-05-05 15:38:26.880000     58.147500  3.442489e+11
min           1931-01-02 00:00:00     21.000000  4.428780e+07
25%           1949-08-10 18:00:00     39.000000  9.662505e+10
50%           1967-12-30 00:00:00     58.500000  4.473258e+11
75%           1987-03-08 06:00:00     77.000000  4.476610e+11
max           2005-12-27 00:00:00     95.000000  4.479992e+11
std                           NaN     21.564889  1.762986e+11

In [9]:
constituents_df.describe()

                    Date of Birth           Age  Phone Number
count                       10000  10000.000000  9.502000e+03
mean   1968-05-05 15:38:26.880000     58.147500  3.442489e+11
min           1931-01-02 00:00:00     21.000000  4.428780e+07
25%           1949-08-10 18:00:00     39.000000  9.662505e+10
50%           1967-12-30 00:00:00     58.500000  4.473258e+11
75%           1987-03-08 06:00:00     77.000000  4.476610e+11
max           2005-12-27 00:00:00     95.000000  4.479992e+11
std                           NaN     21.564889  1.762986e+11

In [8]:
donors_df = constituents_df[ constituents_df['Deceased'].notna() ]
donors_df

,Full Name,Gender,Date of Birth,Age,Deceased,Nationality,Home City,Home Country,Phone Number,Email
Alumni ID,,,,,,,,,,
29,William ElmJones,Male,1932-01-09,94,Yes,British,London,United Kingdom,4.478443e+11,welmjones@abbeywood.ac.uk
31,Isla GlenParker,Male,1935-02-12,91,Yes,British,Manchester,United Kingdom,4.478588e+11,iglenparker@abbeywood.ac.uk
34,evan DaleWright,Male,1936-01-20,90,Yes,British,Birmingham,United Kingdom,4.475414e+11,edalewright@abbeywood.ac.uk
35,Thomas KirkWilson,Female,1932-04-18,94,Yes,British,London,United Kingdom,4.472160e+11,tkirkwilson@abbeywood.ac.uk
53,Evans CedarRoberts,Male,1931-08-12,95,Yes,Spanish,Paris,France,NaN,ecedarroberts@abbeywood.ac.uk
...,...,...,...,...,...,...,...,...,...,...
9944,Olivia OakBrown,Female,1931-12-28,95,Yes,British,Birmingham,United Kingdom,4.475466e+11,ooakbrown@abbeywood.ac.uk
9949,Jenisha ElmSmith,Female,1937-12-03,89,Yes,British,London,United Kingdom,4.478573e+11,jelmsmith@abbeywood.ac.uk
9950,Thomas GlenParker,Female,1931-12-08,95,Yes,British,Birmingham,United Kingdom,4.471632e+11,tglenparker@abbeywood.ac.uk
9980,Evans ParkHill,Male,1937-05-09,89,Yes,Nigerian,Cape Town,South Africa,2.288345e+10,eparkhill@abbeywood.ac.uk
9991,Ella ElmBrown,Female,1935-12-21,91,Yes,British,London,United Kingdom,4.470742e+11,eelmbrown@abbeywood.ac.uk

In [10]:
donors_df.plot()

Error in callback <function _draw_all_if_interactive at 0x0000013E5DCC81A0> (for post_execute), with arguments args (),kwargs {}:

OverflowError: int too big to convert

OverflowError: int too big to convert